name: Telegram Grabber Bot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Устанавливаем Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Шаг 3: Устанавливаем зависимости из requirements.txt (если файл существует)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Запускаем бота (или другие команды для запуска)
      - name: Run the bot
        run: |
          python main.py
